<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit750633cc57e824bcb166221e306ebf2d
{
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
